package com.techshroom.mods.common.test;

import java.util.Arrays;

import com.google.common.collect.ImmutableList;
import com.techshroom.mods.common.Proxy;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.ModMetadata;

/**
 * Proxy mod container.
 * 
 * @author Kenzie Togami
 */
public class ProxyModContainer
        extends DummyModContainer {
    private final Proxy proxy;

    /**
     * Create a container with the Proxy acting as the mod.
     * 
     * @param proxy
     *            - the mod object
     */
    public ProxyModContainer(Proxy proxy) {
        super(new ModMetadata());
        ModMetadata mm = getMetadata();
        mm.authorList = Arrays.asList("Kenzie Togami");
        mm.autogenerated = false;
        mm.childMods = ImmutableList.of();
        mm.credits = "Nobody, who do you think wrote this?";
        mm.dependants = ImmutableList.of();
        mm.dependencies = ImmutableList.of();
        mm.description = "A proxy container for testing";
        mm.modId = "tsmodcore:proxy";
        mm.name = "TSModCore proxy";
        mm.version = "3";
        this.proxy = proxy;
    }
    
    @Override
    public Object getMod() {
        return proxy;
    }
}
