language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install: chmod +x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
after_success: ./gradlew uploadArchives -S

env:
  global:
    TERM=dumb

cache:
    directories:
    - $HOME/.gradle
sudo: false
